### PR TITLE
OADP-612: Pass storageclass and  volumeclass to volsync replication source/destination

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Related CSI plugin PR: https://github.com/openshift/velero-plugin-for-csi/pull/30

### CODE REVIEW

**Review by savitharaghunathan — APPROVED** [review]
/lgtm

**Comment by savitharaghunathan** [comment]
@shubham-pampattiwar Do we wanna add validations for these fields, to ensure if the resources are present in the cluster or not?

**Review by eemcmullan — APPROVED** [review]

**Comment by shubham-pampattiwar** [comment]
> @shubham-pampattiwar Do we wanna add validations for these fields, to ensure if the resources are present in the cluster or not?

@savitharaghunathan We already have these right ? https://github.com/konveyor/volume-snapshot-mover/blob/43f33b3b441cae6a031f172d5cb49f2c0a91f933/controllers/validator.go#L41

Let me know if I misunderstood

**Comment by savitharaghunathan** [comment]
Oh yes. Never mind then. It's all good from my side now. I got confused with the validation func name.

**Pull request merged**
