### PR TITLE
Fix controller logging format

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Fixes: https://github.com/konveyor/volume-snapshot-mover/issues/84
Log Sample of this change:
```
ts=2022-07-21T10:23:08.374573888Z level=info logger=controller.volumesnapshotbackup msg="Shutdown signal received, waiting for all workers to finish" reconcilergroup=datamover.oadp.openshift.io reconcilerkind=VolumeSnapshotBackup
ts=2022-07-21T10:23:08.37461033Z level=info logger=controller.volumesnapshotbackup msg="All workers finished" reconcilergroup=datamover.oadp.openshift.io reconcilerkind=VolumeSnapshotBackup

```
Fix reference: https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
Thanks for linking the article @shubham-pampattiwar . Super helpful

**Comment by savitharaghunathan** [comment]
@shubham-pampattiwar Should we match the log structure to what we have for OADP controller? eg:
```2022-07-21T13:24:33.724Z	INFO	controller.dataprotectionapplication	got provider secret name: cloud-credentials	{"reconciler group": "oadp.openshift.io", "reconciler kind": "DataProtectionApplication", "name": "velero-sample", "namespace": "openshift-adp"}```

**Review by eemcmullan — APPROVED** [review]

**Comment by shubham-pampattiwar** [comment]
> @shubham-pampattiwar Should we match the log structure to what we have for OADP controller? eg: `2022-07-21T13:24:33.724Z INFO controller.dataprotectionapplication got provider secret name: cloud-credentials {"reconciler group": "oadp.openshift.io", "reconciler kind": "DataProtectionApplication", "name": "velero-sample", "namespace": "openshift-adp"}`

@savitharaghunathan Updated the PR to compy with RFC339, now the logs look:
```
2022-07-22T17:00:19Z    INFO    controller.volumesnapshotrestore        Starting EventSource    {"reconciler group": "datamover.oadp.openshift.io", "reconciler kind": "Volum
eSnapshotRestore", "source": "kind source: *v1.VolumeSnapshotContent"}                                                                                                       
2022-07-22T17:00:19Z    INFO    controller.volumesnapshotbackup Starting Controller     {"reconciler group": "datamover.oadp.openshift.io", "reconciler kind": "VolumeSnapsho
tBackup"}    
````

**Review by savitharaghunathan — APPROVED** [review]
/lgtm

**Pull request merged**
